### ISSUE TITLE
Complete commands description

### ISSUE THREAD

**Issue by krucios** [GeeksSect/VirtualMachine#4]
Full description of commands should be created:

1) cmd name
2) cmd opcode
3) cmd flags & cmd modifications 
i.e. 
1: add rax, rbx
2: add [rax], rbx
two modifications of one command

**Comment by HaraldZealot** [comment]
4b01e889d4747158622a2468129997b1be898ed6
39ccb1bc9b308069b5d953e59dd857c84c10ad29
18ed848cbc657df60d5b74e9ba4c7148649e0b26
02188c2682e41e028048d5b1fd0f8c95b2f3a328
e05c1b695c008aae910e0cc431d6f8ce297af9e5
