### ISSUE TITLE
Получены ошибочные данные при исполнении команды

### ISSUE THREAD

**Issue by krucios** [GeeksSect/VirtualMachine#7]
На текущем коммите (b8ab144e7d0bfd11b52d55eef5fe9a23689e8fc6)

![Image Bug screenshot](http://firepic.org/images/2015-04/13/0g2k1buvk1qc.png)

Возможно я ошибся в загрузке данных в память. Вот код:

``` D
void main(string[] args)
{
    try
    {
        auto memory = Storage(0xF000, TypeOfStorage.RAM);
        memory.write(0x00, 0x00_33_FF_11u);
        memory.write(0x04, 0x10u);
        memory.write(0x08, 0x00u);
        memory.write(0x0C, 0x04u);
        writeln(memory.read(0x00, 16));
        auto vm = ProcessorCore(&memory);
        vm.loadProgramm(0x00);
        vm.runOneCommand();
        vm.runOneCommand();
        vm.runOneCommand();
        vm.runOneCommand();
    }
    catch(Exception e)
    {
        stderr.writeln(e.msg);
    }
    stdin.readln();
}
```

В любом случае, гляньте пожалуйста

**Comment by HaraldZealot** [comment]
Усё карэктна, у нас lowendianess.

Гэта значыцца першым ідзе малодшы байт лічбы

**Comment by krucios** [comment]
Прошу прощения, не совсем сначала разобрался с системой загрузки в локальный регистр и потом в операнды. ДействительноЮ всё работает :)
